### ISSUE TITLE
Singlepoint 无法运行

### ISSUE THREAD

**Issue by shuoyuanxu** [LStudioLoren/SatellitePosition#12]
错误如下，请问是不是上传之前误删除了部分代码呢？还是提供的data文件和实际运行的不一样？
Traceback (most recent call last):
  File "D:/Desktop/SatellitePosition-master/position/singlepoint/singlepoint.py", line 15, in <module>
    rtkParam = SINGLEPOINTPOSITION.SinglePointPosition().exesinglepoint(OBS_DATA[0], nav_data_list, rtkParam)
  File "D:\Desktop\SatellitePosition-master\position\singlepoint\SINGLEPOINTPOSITION.py", line 393, in exesinglepoint
    sppparm = self.estpos(nav_list, OBS_DATA, sol)
  File "D:\Desktop\SatellitePosition-master\position\singlepoint\SINGLEPOINTPOSITION.py", line 122, in estpos
    spparm = self.rescode(nav_list, OBS_DATA, rr, pos, err, dtr, V, Var, sol.gpssec).reV()
  File "D:\Desktop\SatellitePosition-master\position\singlepoint\SINGLEPOINTPOSITION.py", line 215, in rescode
    return s
UnboundLocalError: local variable 's' referenced before assignment

**Comment by shuoyuanxu** [comment]
找到问题了，NAVDATA 应该不太对

**Comment by CarpHowling** [comment]
那么您有没有合适的数据分享下
